import { createSlice } from "@reduxjs/toolkit";

interface FileState {
  type: 'file';
  name: string;
  file: File;
  size: number;
  path: string;
  percentage?: number;
  isPaused?: boolean;
  uploadId?: string;
  chunkSize?: number;
  totalChunks?: number;
  uploadedChunks?: number[];
  error?: string;
  lastActivity?: Date;
  fileHash?: string;
  status?:
    | "idle"
    | "initiating"
    | "uploading"
    | "completed"
    | "paused"
    | "cancelled"
    | "error";
}

interface FileUploadState {
      filesWaitingForUpload: FileState[]
      filesUploading: FileState[]
      filesUploaded: FileState[]
}

const initialState: FileUploadState = {
  filesWaitingForUpload: [],
  filesUploading: [],
  filesUploaded: [],
};

export const fileUploadSlice = createSlice({
  name: "fileUpload", // A unique identifier for the slice
  initialState,
  reducers: {
    setFilesWaitingForUpload: (state, action: { payload: FileState[] }) => {
      state.filesWaitingForUpload = action.payload
    },
    setFilesUploading: (state, action: { payload: FileState[] }) => {
      state.filesUploading = action.payload
    },
    setFilesUploaded: (state, action: { payload: FileState[] }) => {
      state.filesUploaded = action.payload
    },
  } 
});

// Export the actions generated by the slice
export const { setFilesUploaded, setFilesUploading, setFilesWaitingForUpload } = fileUploadSlice.actions;

// Export the counter reducer
export default fileUploadSlice.reducer;
