import { createSlice } from "@reduxjs/toolkit";

 

export interface UploadQueueState {
  type: 'file';
  name: string;
  file: File;
  size: number;
  path: string;
  percentage?: number;
  isPaused?: boolean;
  uploadId?: string;
  chunkSize?: number;
  totalChunks?: number;
  uploadedChunks?: number[];
  error?: string;
  lastActivity?: Date;
  fileHash?: string;
  status?:
    | "idle"
    | "initiating"
    | "uploading"
    | "completed"
    | "paused"
    | "cancelled"
    | "error"; 
}
interface FileUploadState {
      uploadQueue: UploadQueueState[] 
}

const initialState: FileUploadState = {
     uploadQueue: [], 
};


/**
 * only handle ui logic here
 */

export const fileUploadSlice = createSlice({
  name: "fileUpload", // A unique identifier for the slice
  initialState,
  reducers: {
    setFilesWaitingForUpload: (state, action: { payload: UploadQueueState[] }) => {
      console.log(action.payload)
      action.payload.map((file) => {
        file.status = "initiating";
      })
      state.uploadQueue = action.payload
    },
    pauseUploadProcess:(state, action: { payload: { positionIndex:number } })=>{
      for(let i = 0; i < state.uploadQueue.length; i++){
        if(i === action.payload.positionIndex){
          state.uploadQueue[i].isPaused = !state.uploadQueue[i].isPaused
        }
      }
    },
    cancelUploadProcess:(state, action: { payload: { positionIndex:number } })=>{
      for(let i = 0; i < state.uploadQueue.length; i++){
        if(i === action.payload.positionIndex){
          state.uploadQueue[i].status = 'cancelled'
        }
      }
    },

    updateUploadQueue:(state, action: { payload: { positionIndex:number, uploadPayload: {percentage?: number, status?:"idle" | "initiating" | "uploading" | "completed" | "paused" | "cancelled" | "error", isPaused?: boolean} } })=>{
      for(let i = 0; i < state.uploadQueue.length; i++){
        if(i === action.payload.positionIndex){
          state.uploadQueue[i] = {...state.uploadQueue[i], ...action.payload.uploadPayload}
        }
      }
    },

    cancelAllCurrentUploads:(state)=>{
      for(let i = 0; i < state.uploadQueue.length; i++){
        state.uploadQueue[i].status = 'cancelled'
      }
    }
  } 
});

// Export the actions generated by the slice
export const { setFilesWaitingForUpload, pauseUploadProcess, cancelUploadProcess, updateUploadQueue, cancelAllCurrentUploads } = fileUploadSlice.actions;

// Export the counter reducer
export default fileUploadSlice.reducer;
