import { ProfileDetails } from "@/Layout/hooks/useGetProfile";
import { createSlice } from "@reduxjs/toolkit";


// Define the type for the counter state
interface ProfileState {
  value: number;
  profile:ProfileDetails | undefined
}

// Define the initial state for the counter
const initialState: ProfileState = {
  value: 0,
  profile: undefined
};


export const profileSlice = createSlice({
  name: "profileSlice", // A unique identifier for the slice
  initialState,
  reducers: {
     setProfile: (state,action) => {state.profile = action.payload},
  }
});

// Export the actions generated by the slice
export const { setProfile } = profileSlice.actions;

// Export the counter reducer
export default profileSlice.reducer;
